### ISSUE TITLE
apply button on chat to apply changes on cursor

### ISSUE THREAD

**Issue by PRANJALRANA11** [aquila-lab/superflex-vscode#10]
there can be an apply button on code snippet to get the code inserted on cursor

![image](https://github.com/user-attachments/assets/7374c2a8-6a9d-4877-a49a-d08a3ac7b63f)

**Comment by Riphal** [comment]
Good idea. Actually, we are working on a fast apply feature to enable users to apply suggested changes to a file without having to look for where the code needs to be pasted.

**Comment by Riphal** [comment]
Closing this issue since we already have fast apply in the backlog.
