### ISSUE TITLE
Facing issue while chatting with the context 

### ISSUE THREAD

**Issue by PRANJALRANA11** [aquila-lab/superflex-vscode#8]
What's the issue
--> when i was searching with the context it is giving internal server error

Here is the ss :

![image](https://github.com/user-attachments/assets/078516fc-e172-47b1-861e-910c8bd4a260)

also I tried to figure out the error so attaching the ss for console also 

![image](https://github.com/user-attachments/assets/ae80ccef-7637-41dc-81f6-282f131e4679)
![image](https://github.com/user-attachments/assets/e8c992ba-65b0-4d84-a068-4d42157563a4)

**Comment by PRANJALRANA11** [comment]
@Riphal I think there is an issue while parsing the big files or so

**Comment by PRANJALRANA11** [comment]
@Riphal gotcha found out the error ! what is happening is when i am adding the context file by clicking the add button then it's working fine but when the file gets selected on tab change it's giving internal server error

**Comment by aibek-yegemberdin** [comment]
Hi Pranjal, thank you for spotting the error! @Riphal is offline for the next few hours but we will respond as soon as we can.

**Comment by PRANJALRANA11** [comment]
@aibek-yegemberdin  could you assign this to me

**Comment by Riphal** [comment]
Hi Pranjal, thanks for offer to contribute! 🤩 
I just assigned this ticket to you. Let's go over the call. I texted you my Calendly link in LinkedIn so I can onboard you to the project.
